name: App Deployment Pipeline
run-name: ${{ github.actor }} is running the app deployment pipeline 🚀

on:
  workflow_dispatch:
#on:
#  push:
#    branches:
#      - main
#    paths:
#      - app/**

jobs:
  app-deployment-pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
        
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

    ## Secret Scanning
      - name: Git Secret Scanning
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    ## SAST Scanning
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v3.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: app
          args: >
                -Dsonar.organization=santhosh-devops-demo
                -Dsonar.projectKey=santhosh-devops-demo_scb-assignment
                -Dsonar.sources=.
                -Dsonar.verbose=true

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hello-app .   

      - name: Docker Images
        run: docker images
        
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'docker.io/santhoshnc/hello-app:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-app

      - name: Collect logs and send to CloudWatch
        run: |
          # Get the current GitHub Actions run ID for log stream naming
          LOG_STREAM="run-${{ github.run_id }}-${{ github.run_number }}"
          LOG_GROUP=${{ vars.CLOUDWATCH_LOG_GROUP }}
          
          # Create log stream
          aws logs create-log-stream --log-group-name $LOG_GROUP --log-stream-name $LOG_STREAM || true

          # Download logs artifact
          echo "Downloading logs artifact..."
          curl -L -o github-actions-logs.log \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ steps.upload-logs.outputs.artifact-id }}/zip"

          # Extract logs from artifact
          unzip github-actions-logs.log -d /tmp/
          LOG_FILE="/tmp/github-actions-logs.log"

          # Convert logs to CloudWatch format
          LOG_EVENTS=$(jq -R -s -c 'split("\n") | map(select(length > 0)) | map({timestamp: (now | floor * 1000), message: .})' < $LOG_FILE)

          # Upload logs to CloudWatch
          aws logs put-log-events --log-group-name $LOG_GROUP --log-stream-name $LOG_STREAM --log-events "$LOG_EVENTS"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          CLOUDWATCH_LOG_GROUP: ${{ vars.CLOUDWATCH_LOG_GROUP }}
