name: Infra Creation Pipeline
run-name: ${{ github.actor }} is running the infra creation pipeline 🚀

on:
  workflow_dispatch:
    inputs:
      appName:
        description: "Enter the app name to be created(Should be a unique name). Don't use spaces or special characters"
        required: true
        type: string

env:
  AWS_REGION: us-west-2
  TF_VAR_app_name: ${{ github.event.inputs.appName }}

jobs:
  create-infra-job:
    name: Create Infra Job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tf
    steps:
      - name: Check out code
        uses: actions/checkout@v4

    ## Secret Scanning
      - name: Git Secret Scanning
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    ## TFLint
      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
          tflint_version: latest

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: tflint -f compact

    ## Checkov
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          # This will add both a CLI output to the console and create a results.sarif file
          output_format: cli,sarif
          output_file_path: console,results.sarif
          soft_fail: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Format
        id: format
        run: terraform fmt

    ## Possible Steps that could be added - Start
      - name: TFSec
        id: tfsec
        run: echo "## To be added - tfsec"

      - name: Open Policy Agent
        id: opa
        run: echo "## To be added - OPA"

      - name: Functional Testing - Terratest
        id: terratest
        run: echo "## To be added - Terratest"
    ## Possible Steps that could be added - End

      - name: Terraform Plan
        id: plan
        run: terraform plan

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
